title: MASA Running Logs
theme: minima
url: "https://humpbacktail.github.io"
baseurl: "/running-logs"

collections:
  logs:
    output: true
    permalink: /logs/:name.html

include:
  - stats.json
  
exclude:
  - logs/template.md.tpl

defaults:
  - scope:
      type: logs
      path: ""
    values:
      layout: page
      nav_exclude: true

  - scope:
      type: pages
      path: ""
    values:
      layout: page

render_with_liquid: false
