title: MASA Running Logs
theme: minima
url: "https://humpbacktail.github.io"
baseurl: "/running-logs"        # ← リポジトリ名と一致
collections:
  logs:
    output: true
    permalink: /logs/:name/
exclude:
  - logs/template.md.tpl        # ← テンプレは除外（そのままでOK）
