title: MASA Running Logs
theme: minima
url: "https://humpbacktail.github.io"
baseurl: "/running-logs"        # ← リポジトリ名と一致

collections:
  logs:
    output: true
    permalink: /logs/:name.html

exclude:
  - logs/template.md.tpl        # ← テンプレは除外（そのままでOK）
  - scripts/**         # （任意）自動化スクリプト群があれば除外
  - README.md          # （任意）/README を公開不要なら
  
  # ここから追加
defaults:
  - scope:
      type: logs        # コレクション名（_logs）に対応
      path: ""          # コレクション内の全ドキュメント
    values:
      nav_exclude: true # ヘッダーナビから除外